graph LR   
subgraph "Composable Information Machine - 'cim'"
SOT{Source of Truth} -->|projects into| sotAPI[API] -->|adapts for| SOR{System of Record} -->|projects into| rmAPI[API] -->|policies/transforms into| RM[Read Model]
RM -->|input deltas| acl[ACL/Filters] --> SOT
end